#!/usr/bin/env python3
"""RUNBOOK GENERATOR.

"Every actionable monitor has a runbook" is only credible if there is a runbook
for all 151 archetypes. Writing 151 documents by hand produces 151 stale
documents, so instead the platform GENERATES a structured first draft from the
archetype catalog — the parts a machine genuinely knows (what fired, why it
fired, what it means, which SLO, which automation, which grouping) — and marks
the parts that need a human with `TODO(owner)`.

Generated sections are regenerated on every catalog change so they cannot go
stale. Human-authored sections are preserved: the generator only rewrites the
block between the AUTOGENERATED markers.

  python tools/generate_runbooks.py            # write/refresh drafts
  python tools/generate_runbooks.py --check    # CI: fail if drafts are stale
  python tools/generate_runbooks.py --report   # how many sections still need a human
"""
from __future__ import annotations

import argparse
import sys

import obs_common as oc

RUNBOOK_DIR = oc.PLATFORM_DIR / "runbooks"

BEGIN = "<!-- AUTOGENERATED:BEGIN -->"
END = "<!-- AUTOGENERATED:END -->"

DETECTION_MEANING = {
    "anomaly": ("the signal deviated from its own learned baseline by more than the "
                "configured number of deviations. It did NOT cross a fixed number, so "
                "'the value looks normal to me' is not a reason to close this"),
    "seasonal_anomaly": ("the signal deviated from its learned SEASONAL baseline — same "
                         "hour, same day of week. Normal daily and weekly cycles are "
                         "already accounted for"),
    "forecast": ("extrapolating the recent trend, the resource is projected to cross its "
                 "limit inside the forecast horizon. It has NOT crossed it yet — the lead "
                 "time is the point of this alert"),
    "outlier": ("this member diverged from its peer group. Every peer receives comparable "
                "work, so divergence is itself the defect"),
    "rate_of_change": ("the signal changed faster than the configured percentage relative "
                       "to its own recent history. Speed of degradation, not absolute level"),
    "threshold": "a fixed threshold was crossed",
    "service_check": "a check reported a non-OK status for consecutive evaluations",
    "event": "a discrete platform event matched this monitor's search",
    "slo_burn": "error budget is being consumed faster than sustainable",
}

IMPACT_TEXT = {
    "customer_impact": ("Customers are affected now, or a mission-critical capability is "
                        "unavailable. Treat as an outage until proven otherwise."),
    "degradation": ("The service still functions but measurably worse; a subset of traffic "
                    "or users is failing."),
    "risk": ("Nothing is broken yet. A boundary will be crossed if nobody acts within the "
             "lead time this monitor provides."),
    "hygiene": ("Observability or configuration hygiene is degraded. No direct customer "
                "impact, but our ability to see or govern the estate is reduced."),
}


def render(policy: dict, aid: str, a: dict) -> str:
    slo = policy["slos"].get(a["slo_id"], {})
    wf = policy["workflows"].get(a["workflow"], {})
    domain = policy["domains"][a["domain"]]
    team = domain.get("routing_override_team", domain["owner_team"])
    grouping = ", ".join(f"`{k}`" for k in a.get("group_by", [])) or "not grouped"
    collapse = ", ".join(f"`{k}`" for k in a.get("notify_by", [])) or "none"
    instances = [i for i in oc.expand_instances(policy) if i["archetype"] == aid]
    envs = sorted({i["env"] for i in instances})
    prios = sorted({i["priority"] for i in instances})
    pages = any(i["pages"] for i in instances)

    body = [
        f"# Runbook: {a['title']}",
        "",
        BEGIN,
        "*This block is generated from `platform/policy/archetypes/` by",
        "`tools/generate_runbooks.py`. Edit the catalog, not this text. Sections below",
        "the marker are yours.*",
        "",
        "| | |",
        "|---|---|",
        f"| Archetype | `{aid}` |",
        f"| Domain | {domain['display']} (owner `{team}`) |",
        f"| Signal | `{a['signal']}` · impact class `{a['impact_class']}` |",
        f"| Detection | `{a['detection']}` |",
        f"| Environments | {', '.join(envs) or '—'} |",
        f"| Priority | {', '.join(prios)} · {'**pages the on-call rotation**' if pages else 'does not page'} |",
        f"| SLO | `{a['slo_id']}` — {slo.get('name', 'unknown')} (target {slo.get('target', '?')}%) |",
        f"| Automation | `{a['workflow']}` ({wf.get('class', '?').replace('_', ' ')}) |",
        f"| Grouping | {grouping} · collapse: {collapse} |",
        f"| Failure domain | `{a['failure_domain']}` (correlation key prefix) |",
        "",
        "## Meaning",
        "",
        f"This monitor fired because {DETECTION_MEANING.get(a['detection'], 'the condition matched')}.",
        "",
        f"Query:",
        "",
        "```",
        a["query"],
        "```",
        "",
    ]
    if a.get("rationale_fixed_threshold"):
        body += [
            "**Why this threshold is a fixed number.** "
            + " ".join(a["rationale_fixed_threshold"].split()),
            "",
        ]
    if a.get("notes"):
        body += ["**Design note.** " + " ".join(a["notes"].split()), ""]

    body += [
        "## Impact",
        "",
        IMPACT_TEXT[a["impact_class"]],
        "",
        f"Error budget: this condition is associated with `{a['slo_id']}`. If the alert is "
        "sustained, expect burn-rate alerts on that objective to follow.",
        "",
        "## Automation",
        "",
        f"Workflow `{a['workflow']}` ({wf.get('class', 'unknown').replace('_', ' ')}) runs "
        f"{'automatically on every alert' if wf.get('class') == 'diagnostic_only' else 'when triggered'}.",
        "",
    ]
    if wf.get("actions"):
        body.append("Actions: " + ", ".join(f"`{x}`" for x in wf["actions"]) + ".")
        body.append("")
    if wf.get("attaches"):
        body.append(f"Attached to the alert automatically: {wf['attaches']}.")
        body.append("")
    if wf.get("guardrails"):
        body.append("Guardrails before anything is changed:")
        body.append("")
        body += [f"- {x}" for x in wf["guardrails"]]
        body.append("")

    body += [
        "## Escalation",
        "",
        f"1. Owning team: `{team}` (see `platform/policy/teams.yaml` for the channel and "
        "ServiceNow assignment group).",
        f"2. Escalates to: `{policy['teams'][team]['escalation_to']}`.",
        f"3. Priority contract: {', '.join(prios)} — "
        + ("ack within 5 minutes, escalate at 10." if "P1" in prios
           else "ack within 10 minutes, escalate at 20." if "P2" in prios
           else "next business day; this never pages."),
        "",
        END,
        "",
        "## Validation",
        "",
        "TODO(owner): how does a responder confirm this is real in under two minutes?",
        "Name the dashboard, the query, or the check to run first.",
        "",
        "## Likely causes",
        "",
        "TODO(owner): the three causes that actually account for most occurrences,",
        "most likely first.",
        "",
        "## Diagnostic queries",
        "",
        "TODO(owner): copy-pasteable queries. The automation above already attaches the",
        "standard set; list what it cannot.",
        "",
        "## Dependency checks",
        "",
        f"TODO(owner): which upstreams to check for `{a['failure_domain']}`, and how to tell",
        "quickly whether the cause is here or upstream.",
        "",
        "## Remediation",
        "",
        "TODO(owner): the safe fix, with the blast radius stated. If a step is dangerous,",
        "say so and require a second pair of eyes.",
        "",
        "## Recovery verification",
        "",
        "TODO(owner): what must be true before this is considered resolved, and how to",
        "confirm the error budget stopped burning.",
        "",
    ]
    return "\n".join(body) + "\n"


def merge(existing: str, generated: str) -> str:
    """Replace only the generated block, preserving human-authored sections."""
    if BEGIN not in existing or END not in existing:
        return generated
    new_block = generated[generated.index(BEGIN):generated.index(END) + len(END)]
    head = existing[:existing.index(BEGIN)]
    tail = existing[existing.index(END) + len(END):]
    return head + new_block + tail


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if any draft is stale")
    ap.add_argument("--report", action="store_true", help="report human-authoring backlog")
    args = ap.parse_args()

    policy = oc.load_policy()
    RUNBOOK_DIR.mkdir(parents=True, exist_ok=True)

    stale, written, todo_total = [], 0, 0
    for aid, a in sorted(policy["archetypes"].items()):
        path = RUNBOOK_DIR / f"{aid}.md"
        generated = render(policy, aid, a)
        merged = merge(path.read_text(), generated) if path.exists() else generated
        if path.exists() and path.read_text() == merged:
            pass
        elif args.check:
            stale.append(path.name)
        else:
            path.write_text(merged)
            written += 1
        todo_total += merged.count("TODO(owner)")

    if args.check:
        if stale:
            print(f"RUNBOOK DRAFTS STALE ({len(stale)}): {stale[:10]}"
                  f"{' …' if len(stale) > 10 else ''}")
            print("Run: python tools/generate_runbooks.py")
            return 1
        print(f"runbooks: {len(policy['archetypes'])} in sync")
        return 0

    print(f"runbooks: {written} written/refreshed, "
          f"{len(policy['archetypes'])} total, {todo_total} sections awaiting an owner")
    if args.report:
        print("\nHuman-authoring backlog by domain:")
        by_domain: dict[str, int] = {}
        for aid, a in policy["archetypes"].items():
            text = (RUNBOOK_DIR / f"{aid}.md").read_text()
            by_domain[a["domain"]] = by_domain.get(a["domain"], 0) + text.count("TODO(owner)")
        for d, n in sorted(by_domain.items(), key=lambda kv: -kv[1]):
            print(f"  {d:<16} {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
