#!/usr/bin/env python3
"""RUNBOOK GENERATOR.

Produces one COMPLETE runbook per archetype — the document that gets published
as a Datadog notebook (`type: runbook`) and attached to the monitor through the
monitor's native `assets` field. Because that notebook is what a responder
opens at 3am, it must be finished: every section required by the runbook
standard is generated with real, archetype-specific content, and `TODO` markers
are rejected by CI.

Specificity comes from three places:
  * the catalog          query, metric, thresholds, grouping, SLO, workflow,
                         environments, priority, failure domain
  * the content library  tools/runbook_content.py — per-signal causes and
                         remediation, per-detection reading guidance, per
                         resource-family telemetry pointers
  * the org policy       owning team, ServiceNow assignment group, escalation
                         chain, review cadence

Regenerating is safe: everything between the AUTOGENERATED markers is rewritten
from the catalog, and anything an owner appends after the end marker is kept.

  python tools/generate_runbooks.py            # write/refresh
  python tools/generate_runbooks.py --check    # CI: fail if stale
  python tools/generate_runbooks.py --report   # per-domain summary
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys

import obs_common as oc
from runbook_content import (
    DETECTIONS,
    FAMILIES,
    IMPACT_BUSINESS,
    IMPACT_TECHNICAL,
    RESOURCE_FAMILY,
    SIGNALS,
)

RUNBOOK_DIR = oc.PLATFORM_DIR / "runbooks"

BEGIN = "<!-- AUTOGENERATED:BEGIN -->"
END = "<!-- AUTOGENERATED:END -->"

# Every section the runbook standard requires. publish_runbooks.py enforces the
# same list before anything reaches Datadog.
REQUIRED_SECTIONS = [
    "Purpose and monitored condition",
    "Business and technical impact",
    "Likely causes",
    "Investigation steps",
    "Metrics, logs, traces, dashboards and dependencies",
    "Safe remediation and automation",
    "Rollback procedure",
    "Recovery validation",
    "Escalation path",
    "Owning team",
    "ServiceNow service and CI",
    "Runbook owner and review date",
]

_METRIC_RE = re.compile(r"\b([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)+)\s*\{")


def metrics_in(query: str) -> list[str]:
    """Metric names referenced by the archetype query, in order, de-duplicated."""
    seen, out = set(), []
    for m in _METRIC_RE.findall(query or ""):
        if m not in seen:
            seen.add(m)
            out.append(m)
    return out


def review_date(policy: dict, tier_cadence: str) -> str:
    """Deterministic next-review date.

    Derived from a committed anchor, never from today's date: a document that
    rewrites itself every morning cannot be staleness-checked in CI.
    """
    rb = policy["runbooks_doc"]
    anchor = rb.get("review_anchor", "2026-08-18")
    days = int(rb.get("review_interval_days", 90))
    if isinstance(anchor, dt.date):
        base = anchor
    else:
        base = dt.date.fromisoformat(str(anchor))
    return (base + dt.timedelta(days=days)).isoformat()


def render(policy: dict, aid: str, a: dict) -> str:
    slo = policy["slos"].get(a["slo_id"], {})
    wf = policy["workflows"].get(a["workflow"], {})
    domain = policy["domains"][a["domain"]]
    team_handle = domain.get("routing_override_team", domain["owner_team"])
    team = policy["teams"][team_handle]

    sig = SIGNALS.get(a["signal"])
    det = DETECTIONS.get(a["detection"], DETECTIONS["threshold"])
    fam_key = RESOURCE_FAMILY.get(a["resource_type"], "apm")
    fam = FAMILIES[fam_key]

    instances = [i for i in oc.expand_instances(policy) if i["archetype"] == aid]
    envs = sorted({i["env"] for i in instances})
    prios = sorted({i["priority"] for i in instances})
    pages = any(i["pages"] for i in instances)
    tier_cadence = policy["tiers"]["tier0"].get("review_cadence", "quarterly")

    svc = a["failure_domain"]
    prod_env = "prod" if "prod" in envs else (envs[0] if envs else "prod")
    grouping = ", ".join(f"`{k}`" for k in a.get("group_by", [])) or "not grouped"
    collapse = ", ".join(f"`{k}`" for k in a.get("notify_by", [])) or "none"
    mets = metrics_in(a["query"])
    window = a.get("evaluation_window", "")

    L: list[str] = [
        f"# Runbook: {a['title']}",
        "",
        BEGIN,
        "*Generated from `platform/policy/archetypes/` by `tools/generate_runbooks.py`.*",
        "*Edit the catalog or `tools/runbook_content.py`, not this text. Notes added*",
        "*below the end marker are preserved.*",
        "",
        "| | |",
        "|---|---|",
        f"| Archetype | `{aid}` |",
        f"| Domain | {domain['display']} |",
        f"| Signal | `{a['signal']}` · impact class `{a['impact_class']}` |",
        f"| Detection | `{a['detection']}` |",
        f"| Monitor type | `{a['monitor_type']}` |",
        f"| Environments | {', '.join(envs) or '—'} |",
        f"| Priority | {', '.join(prios) or '—'} · "
        f"{'**pages the on-call rotation**' if pages else 'does not page'} |",
        f"| SLO | `{a['slo_id']}` — {slo.get('name', 'unknown')} "
        f"(target {slo.get('target', '?')}%) |",
        f"| Automation | `{a['workflow']}` ({wf.get('class', '?').replace('_', ' ')}) |",
        f"| Grouping | {grouping} · collapse: {collapse} |",
        f"| Failure domain | `{svc}` |",
        "",
        # ------------------------------------------------------------------ 1
        f"## {REQUIRED_SECTIONS[0]}",
        "",
        f"This monitor watches **{a['signal'].replace('_', ' ')}** for "
        f"`{a['resource_type']}` resources in the {domain['display']} domain. "
        + (f"It measures {sig['measures']}." if sig else ""),
        "",
        f"It fires when {det['reads']}"
        + (f", evaluated over `{window}`." if window else "."),
        "",
        "Condition as deployed:",
        "",
        "```",
        a["query"],
        "```",
        "",
    ]
    th = a.get("thresholds") or {}
    if th:
        L += ["Thresholds: "
              + ", ".join(f"`{k}` = {v}" for k, v in sorted(th.items()) if v is not None)
              + ".", ""]
    L += [f"Scope selector: `{a.get('selector', 'n/a')}`. The alert is evaluated per "
          f"{grouping if a.get('group_by') else 'monitored resource'}"
          + (f" and notifications collapse on {collapse}." if a.get("notify_by") else "."), ""]
    L += [f"**Reading the trigger.** {det['trap']}", ""]
    if a.get("rationale_fixed_threshold"):
        L += ["**Why this threshold is a fixed number.** "
              + " ".join(a["rationale_fixed_threshold"].split()), ""]
    if a.get("notes"):
        L += ["**Design note.** " + " ".join(a["notes"].split()), ""]

    # ---------------------------------------------------------------------- 2
    L += [
        f"## {REQUIRED_SECTIONS[1]}",
        "",
        f"**Business impact.** {IMPACT_BUSINESS[a['impact_class']]}",
        "",
        f"**Technical impact.** {IMPACT_TECHNICAL[a['impact_class']]}",
        "",
        f"**Error budget.** This condition is associated with `{a['slo_id']}` "
        f"({slo.get('name', 'unknown')}, target {slo.get('target', '?')}% over "
        f"{slo.get('timeframe', '30d')}). Sustained firing consumes that budget and will "
        "be followed by burn-rate alerts on the same objective.",
        "",
        f"**Who feels it.** Consumers of `{svc}` in `{prod_env}`"
        + (f", and anything downstream of {', '.join('`' + d + '`' for d in domain.get('failure_domains', [])[:3])}"
           if domain.get("failure_domains") else "") + ".",
        "",
    ]

    # ---------------------------------------------------------------------- 3
    L += [f"## {REQUIRED_SECTIONS[2]}", "", "Most frequent first.", ""]
    for i, (title, detail) in enumerate(sig["causes"] if sig else [], 1):
        # Library details are written as continuations; present them as sentences.
        detail = (detail[0].upper() + detail[1:]) if detail else ""
        L.append(f"{i}. **{title}.**" + (f" {detail}" if detail else ""))
    L.append("")

    # ---------------------------------------------------------------------- 4
    L += [f"## {REQUIRED_SECTIONS[3]}", ""]
    steps = list(sig["investigate"]) if sig else []
    if a.get("group_by"):
        steps.insert(0, f"Read the alert's group tags ({grouping}) to establish scope before "
                        "opening anything else — they name the affected member directly.")
    if wf.get("attaches"):
        steps.append(f"Read what `{a['workflow']}` already attached to the alert "
                     f"({wf['attaches']}) before re-running those checks by hand.")
    for i, s in enumerate(steps, 1):
        L.append(f"{i}. {s}")
    L.append("")

    # ---------------------------------------------------------------------- 5
    L += [
        f"## {REQUIRED_SECTIONS[4]}",
        "",
        f"**Metrics.** " + (", ".join(f"`{m}`" for m in mets) if mets
                            else "see the query above") + ".",
        "",
        f"**Logs.** `{fam['logs'].format(svc=svc, env=prod_env)}`",
        "",
        f"**Traces.** {fam['traces'].format(svc=svc, env=prod_env)}",
        "",
        f"**Where to look.** {fam['telemetry']}",
        "",
        f"**Dashboards.** *Domain — {domain['display']}* for this domain's health; "
        "*Enterprise Overview* for SLO and platform risk; *On-Call* for what else is "
        "paging right now; *Alert Quality Scorecard* if the alert itself looks wrong.",
        "",
        "**Dependencies.** Failure domains in scope: "
        + ", ".join(f"`{d}`" for d in domain.get("failure_domains", [svc]))
        + f". Correlated alerts share the prefix `{svc}.<env>.<service>`, so a platform "
          "cause will already have adopted the application symptoms as children.",
        "",
    ]

    # ---------------------------------------------------------------------- 6
    L += [f"## {REQUIRED_SECTIONS[5]}", "", "Least destructive first. Stop when the "
          "signal recovers — every further step widens the blast radius.", ""]
    for i, s in enumerate(sig["remediate"] if sig else [], 1):
        L.append(f"{i}. {s}")
    L += ["", f"**Automation.** `{a['workflow']}` — {wf.get('class', 'unknown').replace('_', ' ')}"
          + (", read-only" if wf.get("read_only") else "")
          + (f", approval: {wf['approval']}" if wf.get("approval") else "") + "."]
    if wf.get("actions"):
        L.append("Actions: " + ", ".join(f"`{x}`" for x in wf["actions"]) + ".")
    if wf.get("attaches"):
        L.append(f"Attached to the alert automatically: {wf['attaches']}.")
    if wf.get("max_actions_per_hour"):
        L.append(f"Rate cap: {wf['max_actions_per_hour']} actions/hour.")
    if wf.get("guardrails"):
        L += ["", "Guardrails enforced before anything changes:", ""]
        L += [f"- {x}" for x in wf["guardrails"]]
    L.append("")

    # ---------------------------------------------------------------------- 7
    L += [
        f"## {REQUIRED_SECTIONS[6]}",
        "",
        (sig["rollback"] if sig else "Reverse the change that was applied, most recent first."),
        "",
        f"Whatever is changed, record it on the incident. If `{a['workflow']}` performed an "
        + ("automatic action, it is reversible by design — check its run history for the "
           "compensating action." if wf.get("reversible")
           else "action, review its run history before making further changes.")
        + " If the remediation makes the signal worse, revert it before trying the next step: "
          "two simultaneous changes make the cause unknowable.",
        "",
    ]

    # ---------------------------------------------------------------------- 8
    L += [
        f"## {REQUIRED_SECTIONS[7]}",
        "",
        f"Resolved when {sig['recovery'] if sig else 'the condition has cleared'}.",
        "",
        f"1. The monitor returns to OK and stays there for at least one full evaluation "
        f"window{f' (`{window}`)' if window else ''}.",
        f"2. `{a['slo_id']}` has stopped burning; record the budget consumed against the "
        "incident.",
        "3. Any downtime, silence or circuit breaker applied during the incident is removed.",
        "4. The correlation group closes — do not close it while a child alert is still "
        "firing.",
        "",
    ]

    # ---------------------------------------------------------------------- 9
    ack = policy["priorities"]["priorities"]
    p_top = "P1" if "P1" in prios else ("P2" if "P2" in prios else (prios[0] if prios else "P3"))
    pinfo = ack.get(p_top, {})
    L += [
        f"## {REQUIRED_SECTIONS[8]}",
        "",
        f"This archetype runs at {', '.join(prios) or 'P3'}. "
        + (f"At {p_top}: acknowledge within {pinfo.get('ack_minutes', '?')} minutes, "
           f"escalate at {pinfo.get('escalate_minutes', '?')}."
           if pinfo else ""),
        "",
        "1. **Primary on-call**, `" + team_handle + "` rotation — paged immediately."
        if pages else "1. **Owning team**, `" + team_handle + "` — notified, not paged.",
        "2. **Secondary on-call** — after 10 minutes without acknowledgement.",
        "3. **Team lead**, `" + team_handle + "` — after 20 minutes.",
        f"4. **Incident commander / platform leadership** (`{team['escalation_to']}`) — "
        "after 30 minutes, or immediately if the impact is confirmed and widening.",
        "",
        "Escalate early rather than late if the blast radius is growing, if two or more "
        "domains are alerting at once, or if the remediation requires a change nobody "
        "present is authorised to approve.",
        "",
    ]

    # --------------------------------------------------------------------- 10
    L += [
        f"## {REQUIRED_SECTIONS[9]}",
        "",
        f"**{team['name']}** (`{team_handle}`) — {team['email']}",
        "",
        f"- Alert channel: `{team['teams_channel']}` · low-noise: "
        f"`{team['teams_low_noise_channel']}`",
        f"- Escalates to: `{team['escalation_to']}`",
        f"- Domains owned: {', '.join(team.get('domains_owned', [])) or '—'}",
        f"- Support model: {policy['tiers']['tier0']['support_model'] if pages else 'business hours'}",
        "",
    ]

    # --------------------------------------------------------------------- 11
    L += [
        f"## {REQUIRED_SECTIONS[10]}",
        "",
        f"- **Configuration item (CI):** `{svc}` — the failure domain this monitor is "
        f"scoped to.",
        f"- **Business service:** `{slo.get('service', svc)}`",
        f"- **Assignment group:** `{team['servicenow_assignment_group']}`",
        f"- **Record type:** "
        + ("Incident (P1 → SEV-1, P2 → SEV-2) in production; Task in qa/stage."
           if pages else "Task. This archetype does not raise an incident automatically."),
        "",
        "ServiceNow records are raised by the routing rules from the monitor's tags — do not "
        "open one by hand for the same alert, or the incident will be duplicated.",
        "",
    ]

    # --------------------------------------------------------------------- 12
    L += [
        f"## {REQUIRED_SECTIONS[11]}",
        "",
        f"- **Runbook owner:** {team['name']} (`{team_handle}`) — {team['email']}",
        f"- **Reviewed by:** observability-platform (content standard and attachment)",
        f"- **Review cadence:** {tier_cadence}",
        f"- **Next review due:** {review_date(policy, tier_cadence)}",
        f"- **Source of truth:** `platform/policy/archetypes/{a['domain']}.yaml` → `{aid}`",
        "",
        "This runbook is published to Datadog as a notebook and attached to every monitor "
        "generated from this archetype through the monitor's native `assets` field. It is "
        "regenerated on every catalog change, so corrections belong in the catalog or the "
        "content library, never in the published notebook.",
        "",
        END,
        "",
    ]
    return "\n".join(L) + "\n"


def merge(existing: str, generated: str) -> str:
    """Replace the generated block, preserving operator notes after the end marker."""
    if BEGIN not in existing or END not in existing:
        return generated
    new_block = generated[generated.index(BEGIN):generated.index(END) + len(END)]
    head = generated[:generated.index(BEGIN)]          # regenerate the H1 too
    tail = existing[existing.index(END) + len(END):]
    return head + new_block + tail


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if any runbook is stale")
    ap.add_argument("--report", action="store_true", help="per-domain summary")
    args = ap.parse_args()

    policy = oc.load_policy()
    RUNBOOK_DIR.mkdir(parents=True, exist_ok=True)

    stale, written = [], 0
    for aid, a in sorted(policy["archetypes"].items()):
        # An archetype may SHARE another archetype's runbook (api-latency-seasonal
        # points at api-latency-p99). The registry is keyed by runbook id, so
        # generating a file per archetype produced orphan markdown that
        # publish_runbooks.py --check then failed on. Only the archetype that
        # owns its runbook id writes the file.
        if a["runbook"] != aid:
            continue
        path = RUNBOOK_DIR / f"{aid}.md"
        generated = render(policy, aid, a)
        merged = merge(path.read_text(), generated) if path.exists() else generated
        if path.exists() and path.read_text() == merged:
            continue
        if args.check:
            stale.append(path.name)
        else:
            path.write_text(merged)
            written += 1

    if args.check:
        if stale:
            print(f"RUNBOOKS STALE ({len(stale)}): {stale[:10]}"
                  f"{' …' if len(stale) > 10 else ''}")
            print("Run: python tools/generate_runbooks.py")
            return 1
        print(f"runbooks: {len(policy['archetypes'])} in sync")
        return 0

    print(f"runbooks: {written} written/refreshed, {len(policy['archetypes'])} total")
    if args.report:
        by_domain: dict[str, int] = {}
        for aid, a in policy["archetypes"].items():
            by_domain[a["domain"]] = by_domain.get(a["domain"], 0) + 1
        print("\nRunbooks by domain:")
        for d, n in sorted(by_domain.items(), key=lambda kv: -kv[1]):
            print(f"  {d:<16} {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
