#!/usr/bin/env python3
"""MONITOR RECONCILIATION REPORT.

One row per deployed monitor, joining what Terraform planned, what the runbook
registry binds, and what the routing policy resolves to — so "every actionable
monitor has an owner, a route, an escalation policy and an attached runbook" is
a table somebody can audit rather than a claim.

Sources, in order of authority:
  --live        the Datadog API (what is actually deployed)
  --fixtures    tests/fixtures/monitors_planned.json (the plan-derived estate;
                identical to live whenever the idempotency gate is green)

Output: docs/monitor-reconciliation.md (+ .json for machines).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import obs_common as oc

DOC = oc.REPO_ROOT / "docs" / "monitor-reconciliation.md"


def route_for(policy: dict, profile: str, priority: str, pages: bool) -> str:
    """The destinations a monitor's tags resolve to, per notification_profiles."""
    prof = policy["notification_profiles"]["notification_profiles"].get(profile)
    if not prof:
        return "—"
    route = (prof.get("routes") or {}).get(priority.upper())
    if not route:
        return "no route (silent by policy)"
    dests = []
    if pages and route.get("page"):
        dests.append("On-Call page")
    sn = route.get("servicenow", "none")
    if sn.startswith("incident"):
        dests.append(f"ServiceNow {sn.replace('_', ' ')}")
    elif sn.startswith("task"):
        dests.append("ServiceNow task")
    teams = route.get("teams", "team_channel")
    dests.append("Teams low-noise" if "low_noise" in teams else "Teams")
    for ch in route.get("extra_channels", []):
        dests.append(ch.replace("_channel", "").replace("_", " "))
    return " + ".join(dests)


def build(monitors: list[dict], policy: dict) -> list[dict]:
    registry = policy["runbooks"]
    rows = []
    for m in monitors:
        t = oc.tags_to_map(m.get("tags"))
        if t.get("managed_by") != "terraform":
            continue
        rb_id = t.get("runbook", "")
        entry = registry.get(rb_id, {})
        notebook = t.get("runbook_notebook") or str(entry.get("id") or "")
        msg = m.get("message", "")
        pages = t.get("pages") == "true"
        team = t.get("team", "")
        # Datadog's "automatically resolve from a triggered state after N
        # hours". Its default is 0 — never — and a monitor stuck in `Alert`
        # does not fire again for the next occurrence, so this column is a
        # paging-integrity column, not a hygiene one.
        timeout_h = (m.get("options") or {}).get("timeout_h")

        problems = []
        if not notebook:
            problems.append("no runbook attached")
        if not timeout_h:
            problems.append("no auto-resolve")
        if "http://" in msg or "https://" in msg:
            problems.append("URL in message")
        if not t.get("slo_id"):
            problems.append("no SLO")
        if not t.get("automation_ref"):
            problems.append("no workflow")
        if not team:
            problems.append("no owner")
        if pages and t.get("env") != "prod":
            problems.append("pages outside production")

        rows.append({
            "id": m.get("id"),
            "name": m.get("name", ""),
            "service": t.get("service", ""),
            "env": t.get("env", ""),
            "owner": team,
            "priority": (t.get("priority") or "").upper(),
            "pages": pages,
            "route": route_for(policy, t.get("notification_profile", ""),
                               t.get("priority", "p3"), pages),
            "escalation_policy": f"{team} — escalation" if pages else "—",
            "runbook": entry.get("title", rb_id),
            "notebook_id": notebook or "—",
            "attachment": "ATTACHED" if notebook else "MISSING",
            "auto_resolve": f"{timeout_h}h" if timeout_h else "NONE",
            "slo": t.get("slo_id", ""),
            "workflow": t.get("automation_ref", ""),
            "status": "PASS" if not problems else "FAIL: " + "; ".join(problems),
        })
    return sorted(rows, key=lambda r: (r["priority"], r["env"], r["name"]))


def to_markdown(rows: list[dict]) -> str:
    ok = sum(1 for r in rows if r["status"] == "PASS")
    attached = sum(1 for r in rows if r["attachment"] == "ATTACHED")
    paging = sum(1 for r in rows if r["pages"])
    out = [
        "# Monitor reconciliation",
        "",
        "Generated by `tools/reconciliation_report.py`. One row per",
        "Terraform-managed monitor.",
        "",
        f"- Monitors: **{len(rows)}**",
        f"- With a native Datadog runbook attachment: **{attached}/{len(rows)}**",
        f"- Runbook URLs embedded in an alert body: "
        f"**{sum(1 for r in rows if 'URL in message' in r['status'])}**",
        f"- Paging monitors (each with a team escalation policy): **{paging}**",
        f"- With an auto-resolve condition (`timeout_h`): "
        f"**{sum(1 for r in rows if r['auto_resolve'] != 'NONE')}/{len(rows)}**",
        f"- Final validation: **{ok}/{len(rows)} PASS**",
        "",
        "> `ID` is the live Datadog monitor id when generated with `--live` (the",
        "> deploy pipeline does this after every production apply). Under",
        "> `--fixtures` it is the plan ordinal, because a monitor has no id until",
        "> it is applied.",
        "",
        "| Monitor | ID | Service / env | Owner | Sev | Route | Escalation policy "
        "| Runbook | Notebook ID | Attach | Auto-resolve | SLO | Workflow | Status |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        out.append(
            f"| {r['name']} | {r['id']} | {r['service']} / {r['env']} | {r['owner']} "
            f"| {r['priority']} | {r['route']} | {r['escalation_policy']} "
            f"| {r['runbook']} | {r['notebook_id']} | {r['attachment']} "
            f"| {r['auto_resolve']} | {r['slo']} "
            f"| {r['workflow']} | {r['status']} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--live", action="store_true")
    mode.add_argument("--fixtures", type=Path)
    ap.add_argument("--out-md", type=Path, default=DOC)
    ap.add_argument("--out-json", type=Path,
                    default=oc.GENERATED_DIR / "monitor_reconciliation.json")
    args = ap.parse_args()

    if args.live:
        headers, site = oc.dd_headers(), oc.dd_site()
        monitors, page = [], 0
        while True:
            r = oc.dd_request("GET", f"{site}/api/v1/monitor", headers=headers,
                              params={"page": page, "page_size": 200})
            r.raise_for_status()
            batch = r.json()
            monitors.extend(batch)
            if len(batch) < 200:
                break
            page += 1
    else:
        monitors = json.loads((args.fixtures / "monitors_planned.json").read_text())

    policy = oc.load_policy()
    policy["notification_profiles"] = oc._yaml(
        oc.POLICY_DIR / "notification_profiles.yaml")
    rows = build(monitors, policy)

    oc.write_json(args.out_json, rows)
    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.write_text(to_markdown(rows))

    failing = [r for r in rows if r["status"] != "PASS"]
    print(json.dumps({
        "monitors": len(rows),
        "attached": sum(1 for r in rows if r["attachment"] == "ATTACHED"),
        "unattached": sum(1 for r in rows if r["attachment"] == "MISSING"),
        "urls_in_messages": sum(1 for r in rows if "URL in message" in r["status"]),
        "paging": sum(1 for r in rows if r["pages"]),
        "no_auto_resolve": sum(1 for r in rows if r["auto_resolve"] == "NONE"),
        "pass": len(rows) - len(failing),
        "fail": len(failing),
    }, indent=2))
    for r in failing[:20]:
        print(f"  FAIL {r['name']}: {r['status']}")
    return 1 if failing else 0


if __name__ == "__main__":
    sys.exit(main())
